name: PR Approved Workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  print-source-branch:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Print source branch name
        run: echo "Source branch is ${{ github.event.pull_request.head.ref }}"
