name: PR Created Workflow

on:
  pull_request:
    types: [opened]

jobs:
  print-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print source branch name
        run: echo "Source branch is ${{ github.event.pull_request.head.ref }}"
